Create Database BD_COMERCIO
Collate Latin1_General_CI_AI
GO
USE BD_COMERCIO
GO
CREATE TABLE Categorias (
	IDCategoria INT NOT NULL UNIQUE IDENTITY(1,1),
	Categoria NVARCHAR(70) NOT NULL UNIQUE,
	Estado BIT NOT NULL DEFAULT 1,
	PRIMARY KEY(IDCategoria)
);
GO

CREATE TABLE Marcas (
	IDMarca INT NOT NULL UNIQUE IDENTITY(1,1),
	Marca NVARCHAR(70) NOT NULL UNIQUE,
	Estado BIT NOT NULL DEFAULT 1,
	PRIMARY KEY(IDMarca)
);
GO

CREATE TABLE Productos (
	IDProducto BIGINT NOT NULL UNIQUE IDENTITY(1,1),
	NumeroSerie NVARCHAR(70) NOT NULL,
	IDMarca INT NOT NULL,
	IDCategoria INT NOT NULL,
	Nombre NVARCHAR(50) NOT NULL,
	Precio DECIMAL(16,3) NOT NULL,
	StockActual SMALLINT NOT NULL,
	StockMinimo SMALLINT NOT NULL,
	PorcentajeGanancia SMALLINT NOT NULL,
	Modelo NVARCHAR(50) NULL,
	Descripcion NVARCHAR(255) NULL,
	Estado BIT NOT NULL DEFAULT 1,
	PRIMARY KEY(IDProducto),
    FOREIGN KEY (IDMarca) REFERENCES Marcas (IDMarca),
    FOREIGN KEY (IDCategoria) REFERENCES Categorias (IDCategoria)
);
GO

CREATE TABLE Producto_Imagenes (
	IDImagen BIGINT NOT NULL UNIQUE IDENTITY(1,1),
	IDProducto BIGINT NOT NULL,
	Direccion NVARCHAR(255) NOT NULL,
	Estado BIT NOT NULL DEFAULT 1,
	PRIMARY KEY(IDImagen),
    FOREIGN KEY (IDProducto) REFERENCES Productos (IDProducto)
);
GO

CREATE TABLE Personas (
	IDPersona BIGINT NOT NULL UNIQUE IDENTITY(1,1),
	Nombre NVARCHAR(50) NOT NULL,
	Apellido NVARCHAR(50) NOT NULL,
	DNI BIGINT NULL,
	CUIT BIGINT NULL,
	TipoPersona BIT NOT NULL,
	Telefono BIGINT NOT NULL,
	Email NVARCHAR(70) NULL,
	Direccion NVARCHAR(100) NULL,
	Estado BIT NOT NULL DEFAULT 1,
	PRIMARY KEY(IDPersona)
);
GO

CREATE TABLE Usuarios (
	IDUsuario BIGINT NOT NULL UNIQUE IDENTITY(1,1),
	IDPersona BIGINT NOT NULL UNIQUE,
	TipoUsuario NVARCHAR(20) NOT NULL,
	NombreUsuario NVARCHAR(50) NOT NULL UNIQUE,
	Contraseña NVARCHAR(50) NOT NULL,
	Estado BIT NOT NULL DEFAULT 1,
	PRIMARY KEY(IDUsuario),
    FOREIGN KEY (IDPersona) REFERENCES Personas (IDPersona)
);
GO

CREATE TABLE Clientes (
	IDCliente BIGINT NOT NULL UNIQUE IDENTITY(1,1),
	IDPersona BIGINT NOT NULL,
	Estado BIT NOT NULL DEFAULT 1,
	PRIMARY KEY(IDCliente),
    FOREIGN KEY (IDPersona) REFERENCES Personas (IDPersona)
);
GO

CREATE TABLE Proveedor (
	IDProveedor BIGINT NOT NULL UNIQUE IDENTITY(1,1),
	IDPersona BIGINT NOT NULL,
	RazonSocial NVARCHAR(30) NOT NULL,
	Estado BIT NOT NULL DEFAULT 1,
	PRIMARY KEY(IDProveedor),
    FOREIGN KEY (IDPersona) REFERENCES Personas (IDPersona)
);
GO

CREATE TABLE Producto_Proveedor (
	IDPP BIGINT NOT NULL UNIQUE IDENTITY(1,1),
	IDProducto BIGINT NOT NULL,
	IDProveedor BIGINT NOT NULL,
	FechaAlta DATE NOT NULL,
    FechaBaja DATE NULL,
	Estado BIT NOT NULL DEFAULT 1,
	PRIMARY KEY(IDPP),
    FOREIGN KEY (IDProducto) REFERENCES Productos (IDProducto),
    FOREIGN KEY (IDProveedor) REFERENCES Proveedor (IDProveedor)
);
GO

CREATE TABLE Ventas (
	IDVenta BIGINT NOT NULL UNIQUE IDENTITY(1,1),
	IDCliente BIGINT NOT NULL,
	IDUsuario BIGINT NOT NULL,
	NFactura NVARCHAR(50) NOT NULL,
	Fecha DATETIME NOT NULL,
	Total DECIMAL(16,3) NOT NULL,
	Estado BIT NOT NULL DEFAULT 1,
	PRIMARY KEY(IDVenta),
    FOREIGN KEY (IDCliente) REFERENCES Clientes (IDCliente),
    FOREIGN KEY (IDUsuario) REFERENCES Usuarios (IDUsuario)
);
GO

CREATE TABLE Detalle_Venta (
	IDVenta BIGINT NOT NULL,
	IDProducto BIGINT NOT NULL,
	Cantidad SMALLINT NOT NULL,
	PrecioUnitario DECIMAL(16,3) NOT NULL,
	PrecioParcial DECIMAL(16,3) NOT NULL,
	PorcentajeGanancia SMALLINT NOT NULL,
	Estado BIT NOT NULL DEFAULT 1,
	PRIMARY KEY(IDVenta, IDProducto),
    FOREIGN KEY (IDVenta) REFERENCES Ventas (IDVenta),
    FOREIGN KEY (IDProducto) REFERENCES Productos (IDProducto)
);
GO

CREATE TABLE Compras (
	IDCompra BIGINT NOT NULL UNIQUE IDENTITY(1,1),
	IDUsuario BIGINT NOT NULL,
	IDProveedor BIGINT NOT NULL,
	Fecha DATETIME NOT NULL,
	Total DECIMAL(16,3) NOT NULL,
	Estado BIT NOT NULL DEFAULT 1,
	PRIMARY KEY(IDCompra),
    FOREIGN KEY (IDUsuario) REFERENCES Usuarios (IDUsuario),
    FOREIGN KEY (IDProveedor) REFERENCES Proveedor (IDProveedor)
);
GO

CREATE TABLE Detalle_Compra (
	IDCompra BIGINT NOT NULL,
	IDProducto BIGINT NOT NULL,
	Cantidad SMALLINT NOT NULL,
	PrecioUnitario DECIMAL(16,3) NOT NULL,
	PrecioParcial DECIMAL(16,3) NOT NULL,
	Estado BIT NOT NULL DEFAULT 1,
	PRIMARY KEY(IDCompra, IDProducto),
    FOREIGN KEY (IDCompra) REFERENCES Compras (IDCompra),
    FOREIGN KEY (IDProducto) REFERENCES Productos (IDProducto)
);
GO

CREATE TABLE HistorialMovimiento (
	IDHistorial BIGINT NOT NULL UNIQUE IDENTITY(1,1),
	IDProducto BIGINT NOT NULL,
	IDVenta BIGINT NULL,
	IDCompra BIGINT NULL,
	IDUsuario BIGINT NOT NULL,
	StockAnterior SMALLINT NOT NULL,
	StockPosterior SMALLINT NOT NULL,
	Fecha DATETIME NOT NULL,
	Estado BIT NOT NULL DEFAULT 1,
	PRIMARY KEY(IDHistorial),
    FOREIGN KEY (IDProducto) REFERENCES Productos (IDProducto),
    FOREIGN KEY (IDVenta) REFERENCES Ventas (IDVenta),
    FOREIGN KEY (IDCompra) REFERENCES Compras (IDCompra),
    FOREIGN KEY (IDUsuario) REFERENCES Usuarios (IDUsuario)
);
GO